### ISSUE TITLE
potential syntax misunderstanding

### ISSUE THREAD

**Issue by lewisje** [metaphoricgiraffe/tracking-filters#2]
The AOL filter `||*.aolcdn.com/os/aol/beacon.min.js$script` should be just `||aolcdn.com/os/aol/beacon.min.js$script` because the `||` does not mean "filter starts here" but rather "match this domain, and all subdomains, on both HTTP and HTTPS," and it actually is possible to make hiding rules that don't start with the double-pipe.

To be strict, your filter _does_ exclude aolcdn.com itself, while my fixed version doesn't, but that semantic difference shouldn't matter; also, I did not notice any other problems that indicate a potential misunderstanding of ABP filter syntax.

**Comment by metaphoricgiraffe** [comment]
Yes, I forgot that point. Fixed it up now
