### ISSUE TITLE
reddit tracking

### ISSUE THREAD

**Issue by kintpuash** [metaphoricgiraffe/tracking-filters#4]
On reddit there is an unblocked pixel using Fanboy Ultimate. Would it have any function by itself?

reddit.com/static/pixel.png

blocking it seems to have no ill effect.

Additionally, there is an exception to:

www.google-analytics.com/analytics.js$script

Block as well?

**Comment by metaphoricgiraffe** [comment]
Tested blocking the pixel, reddit remains functional.

Don't know why there is an exception for www.google-analytics.com/analytics.js$script, I block all GA and reddit remains functional.
