### ISSUE TITLE
Video thumbnails on YouTube blocked

### ISSUE THREAD

**Issue by anonsubmitter** [metaphoricgiraffe/tracking-filters#5]
The `||s.ytimg.com/yts/img/pixel-*.gif$domain=www.youtube.com` filter rule blocks video thumbnails on YouTube.

**Comment by gituporabnik** [comment]
I can confirm the issue. Besides, this filter rule often seems to break playing YouTube videos.

**Comment by b0nk** [comment]
I can also confirm. It even blocks the channels avatar at the bottom of the video.
Pretty much all images from ytimg.com
Why do these pixels exist?

**Comment by anonsubmitter** [comment]
Embedding small, transparent 1 x 1 pixel images is one of the many ways companies are able to track users.

**Comment by b0nk** [comment]
I know about the tracking but blocking these pixels shouldn't "disable" the thumbnails. The browser downloads the thumbnails (I checked) but refuses to display them. Maybe a script is checking for the pixel and decides to show the thumbnails if it's loaded?

**Comment by metaphoricgiraffe** [comment]
Thank you for your reports. I have removed the filter.
